{
    "name": "Tracking",
    "author": "Yash Shah",
    "summary": """Inherit the report""",
    "description": """inherit sale order report and add a field named tracking.""",
    "website": "https://www.youtube.com",
    "category": "Business",
    "version": "14.0.1.0.0",
    "depends": ["sale_management", "stock"],
    "data": ["report/report.xml",],
    "application": True,
    "installable": True,
    "auto_install": False,
    "sequence": 1,
}
